version: '3'

services:
  node:
    build:
      context: node
    container_name: node
    restart: always
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - node
      - db
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./dump/schema.sql:/docker-entrypoint-initdb.d/schemdoa.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge